language: go

go:
  - 1.12.x

script:
  - env GO111MODULE=on go build
  - chmod +x ./deploy.sh
  - echo "$DOCKER_PASS" | docker login docker.pkg.github.com --username "$DOCKER_USER" --password-stdin
  - docker build -t docker.pkg.github.com/att-cloudnative-labs/kubesweeper/kubesweeper:latest .
  - docker push docker.pkg.github.com/att-cloudnative-labs/kubesweeper/kubesweeper:latest
  - docker logout