apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: {{ .Values.image }}
