kleaner:
  reasons:
    - reason: "CrashLoopBackOff"
      restartThreshold: 144
      deleteFuncString: "DeleteCrash"
    - reason: "ImagePullBackOff"
      deleteFuncString: "DeleteGeneric"
    - reason: "ErrImagePull"
      deleteFuncString: "DeleteGeneric"
    - reason: "Completed"
      deleteFuncString: "DeleteGeneric"
    - reason: "Failed"
      deleteFuncString: "DeleteGeneric"
