apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubesweeper
  namespace: att-cloudnative-labs
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kubesweeper
          containers:
          - args:
            image: docker-registry.aeg.cloud/common-platform/kubesweeper:0.0.0-120619-1
            imagePullPolicy: Always
            name: kubesweeper
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/2 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false