apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubernetes-deployment-crawler
  namespace: kythera-system
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - args:
              image: docker.io/attcloudnativelabs/kubernetes-deployment-crawler:v0.0.1-alpha
              imagePullPolicy: Always
              name: kubernetes-deployment-crawler
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '0 10 * * *'
  successfulJobsHistoryLimit: 3
  suspend: false