apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubesweeper
  namespace: att-cloudnative-labs
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kubesweeper
          containers:
          - args:
            image: docker.pkg.github.com/att-cloudnative-labs/kubesweeper/kubesweeper:latest
            imagePullPolicy: Always
            name: kubesweeper
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '0 10 * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
